### ISSUE TITLE
game froze on loading screen after installing RasterPropMoniter

### ISSUE THREAD

**Issue by joey-lg** [JonnyOThan/RasterPropMonitor#22]
Log file
[KSP.log](https://github.com/JonnyOThan/RasterPropMonitor/files/5279402/KSP.log)
I hope someone can help me out here...

**Comment by JonnyOThan** [comment]
If the game freezes or crashes, your player.log file is more useful to diagnose the issue since ksp.log is not flushed after every line.

I don't see anything obviously wrong, although ROCapsules appears to require ASET props which you don't have installed.

You also don't seem to have a lot of stock squad assets, but maybe Restock is removing them?
